# Generated by Django 5.2.8 on 2025-11-06 02:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="collabSpaceAtlas.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="TopLevelContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "summary",
                    models.TextField(help_text="A short abstract show in listing"),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("est_minutes", models.PositiveIntegerField(default=60)),
                ("license", models.CharField(default="CC BY 4.0", max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("canonical_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="top_level_contents", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="collabSpaceAtlas.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section_key", models.CharField(default="custom", max_length=40)),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("math", "Math"),
                            ("code", "Code"),
                            ("image", "Image"),
                            ("logic", "Logic"),
                            ("quote", "Quote"),
                            ("quiz", "Quiz"),
                            ("output", "Output"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("data", models.JSONField(default=dict)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="collabSpaceAtlas.toplevelcontent",
                    ),
                ),
            ],
            options={
                "ordering": ["section_key", "order"],
            },
        ),
    ]
