# Generated by Django 4.2.20 on 2025-11-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collabSpaceAtlas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toplevelcontent",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="toplevelcontent",
            name="topic",
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={
                "ordering": ["order", "title"],
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
            },
        ),
        migrations.DeleteModel(
            name="ContentBlock",
        ),
        migrations.DeleteModel(
            name="TopLevelContent",
        ),
    ]
