# Generated by Django 4.2.20 on 2025-11-06 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collabSpaceAtlas", "0002_remove_toplevelcontent_authors_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
